package com.user.mapstruct;

import org.springframework.stereotype.Component;

import com.user.dto.UserDataDTO;
import com.user.entity.UserData;

import jakarta.annotation.Generated;

@Component
@Generated(value = "org.mapstruct.ap.MappingProcessor", date = "2025-02-24T12:34:56.789Z", comments = "Generated by MapStruct.")
public class UserMapperStructImpl implements UserMapperStruct {
	@Override
	public UserData toEntity(UserDataDTO dto) {
		if (dto == null) {
			return null;
		}
		return toEntity(dto);
	}

	@Override
	public UserDataDTO toDto(UserData entity) {
		if (entity == null) {
			return null;
		}
		// Mapping logic
		return toDto(entity);
	}

}
